In [1]:
import torch

inputs = torch.tensor(
  [[0.43, 0.15, 0.89], # Your     (x^1)
   [0.55, 0.87, 0.66], # journey  (x^2)
   [0.57, 0.85, 0.64], # starts   (x^3)
   [0.22, 0.58, 0.33], # with     (x^4)
   [0.77, 0.25, 0.10], # one      (x^5)
   [0.05, 0.80, 0.55]] # step     (x^6)
)

# Finding for one input value

In [2]:
query = inputs[1]  

attn_scores_2 = torch.empty(inputs.shape[0])
for i, x_i in enumerate(inputs):
    attn_scores_2[i] = torch.dot(x_i, query) 

print(attn_scores_2)

tensor([0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865])


In [5]:
attn_scores_sumNormalize=attn_scores_2/attn_scores_2.sum()
attn_scores_sumNormalize


tensor([0.1455, 0.2278, 0.2249, 0.1285, 0.1077, 0.1656])

In [8]:
attn_scores_sigmoid=torch.softmax(attn_scores_2,dim=0)
attn_scores_sigmoid


tensor([0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581])

# Computing attention weights for all input tokens

In [16]:
attm_score=torch.empty(inputs.shape[0],inputs.shape[0])
for i,xi in enumerate(inputs):
    for j , xj in enumerate(inputs):
        attm_score[i,j]=torch.dot(xi,xj)

attm_weights=torch.softmax(attm_score,dim=-1)
all_context_vec=attm_weights@inputs
all_context_vec

tensor([[0.4421, 0.5931, 0.5790],
        [0.4419, 0.6515, 0.5683],
        [0.4431, 0.6496, 0.5671],
        [0.4304, 0.6298, 0.5510],
        [0.4671, 0.5910, 0.5266],
        [0.4177, 0.6503, 0.5645]])

# Easy way

In [17]:
attm_score=inputs @ inputs.T

attm_weights=torch.softmax(attm_score,dim=-1)
all_context_vec=attm_weights@inputs
all_context_vec

tensor([[0.4421, 0.5931, 0.5790],
        [0.4419, 0.6515, 0.5683],
        [0.4431, 0.6496, 0.5671],
        [0.4304, 0.6298, 0.5510],
        [0.4671, 0.5910, 0.5266],
        [0.4177, 0.6503, 0.5645]])