In [1]:
import torch
import torch.nn as nn

## Layer normalization 

In [9]:
class LayerNorm(nn.Module):
    def __init__(self,emb_dim):
        super().__init__()
        self.eps=1e-5
        self.scale_params=nn.Parameter(torch.ones(emb_dim))
        self.shift_params=nn.Parameter(torch.zeros(emb_dim))
    
    def forward(self,x):
        mean=x.mean(dim=-1,keepdim=True)
        var=x.var(dim=-1,keepdim=True,unbiased=False)
        norm=(x-mean)/torch.sqrt(var+self.eps)
        return norm*self.scale_params+ self.shift_params
    
torch.manual_seed(123)
batch_example = torch.randn(2, 5) 
ln = LayerNorm(5)
out_ln = ln(batch_example)
print(out_ln)
print(out_ln.mean(dim=-1,keepdim=True))
print(out_ln.var(dim=-1,keepdim=True))


        
        

tensor([[ 0.5528,  1.0693, -0.0223,  0.2656, -1.8654],
        [ 0.9087, -1.3767, -0.9564,  1.1304,  0.2940]], grad_fn=<AddBackward0>)
tensor([[-2.9802e-08],
        [ 0.0000e+00]], grad_fn=<MeanBackward1>)
tensor([[1.2499],
        [1.2500]], grad_fn=<VarBackward0>)


reason for variance not being equal to 1 completly is brcause we are using unbiased = False which dont do basel correction 
but gpt 2 uses unbiased=False so using it as such time being